fix: remove ghost submodule entries, restore yamllint config, fix YAML indentation and REUSE coverage

diff --git a/charts/keycloak-tenant-controller/templates/statefulset.yaml b/charts/keycloak-tenant-controller/templates/statefulset.yaml
--- a/charts/keycloak-tenant-controller/templates/statefulset.yaml
+++ b/charts/keycloak-tenant-controller/templates/statefulset.yaml
@@ -20,10 +20,10 @@ spec:
       labels:
         app: keycloak-tenant-controller-pod
     spec:
-        {{- with .Values.imagePullSecrets }}
+      {{- with .Values.imagePullSecrets }}
       imagePullSecrets:
         {{- toYaml . | nindent 8 }}
-        {{- end }}
+      {{- end }}
       serviceAccountName: {{ .Values.serviceAccount.name }}
       securityContext:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
@@ -59,14 +59,14 @@ spec:
             {{- toYaml .Values.securityContext | nindent 12 }}
           command: ["/bin/sh", "-c"]
           args:
-          - |
-            set -e
-            echo "edge-orchestrator.intel.com, waiting for CR..."
-            echo "Waiting for CR 'orgs.org.infra-host.com' to be available..."
-            until kubectl get orgs.org.edge-orchestrator.intel.com; do
-              echo "orgs.org.edge-orchestrator.intel.com CR not found, waiting..."
-              sleep 10
-            done
+            - |
+              set -e
+              echo "edge-orchestrator.intel.com, waiting for CR..."
+              echo "Waiting for CR 'orgs.org.infra-host.com' to be available..."
+              until kubectl get orgs.org.edge-orchestrator.intel.com; do
+                echo "orgs.org.edge-orchestrator.intel.com CR not found, waiting..."
+                sleep 10
+              done
       volumes:
         - name: ktc-credentials
           configMap:
